"""Regenerate ``schemas/city_input.schema.json`` from the city-builder config.

The JSON schema is derived from :mod:`citygml_energy.city_builder.config`
so IDE autocomplete always reflects the real loader validation. A CI
test (``tests/test_city_input_schema.py``) refuses to let the committed
file drift out of sync.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = REPO_ROOT / "schemas" / "city_input.schema.json"

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from citygml_energy.city_builder.config import (
    ALLOWED_LODS,
    SCHEMA_VERSION,
)
from citygml_energy.namespaces import DEFAULT_SRS_NAME


def build_schema() -> dict[str, Any]:
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://example.invalid/schemas/city_input.schema.json",
        "title": "CityGML Energy City-Build Input",
        "description": (
            "Configuration for the city-scale builder "
            "(citygml_energy.city_builder). Generated by "
            "tools/generate_city_input_schema.py — do not edit by hand."
        ),
        "type": "object",
        "required": ["schema_version", "municipality", "output"],
        "additionalProperties": False,
        "properties": {
            "$schema": {"type": "string"},
            "schema_version": {"const": SCHEMA_VERSION},
            "municipality": {
                "type": "string",
                "minLength": 1,
                "description": (
                    "Dutch municipality name as used by PDOK "
                    "bestuurlijkegebieden (case-insensitive)."
                ),
            },
            "bbox": {
                "type": "array",
                "description": (
                    "Optional [minx, miny, maxx, maxy] in EPSG:28992 to narrow "
                    "the fetch further than the municipality outline."
                ),
                "minItems": 4,
                "maxItems": 4,
                "items": {"type": "number"},
            },
            "lods": {
                "type": "array",
                "description": "Subset of 3DBAG LoDs to attach per building.",
                "items": {"type": "integer", "enum": sorted(ALLOWED_LODS)},
                "minItems": 1,
                "uniqueItems": True,
            },
            "include_addresses": {
                "type": "boolean",
                "description": (
                    "Emit bldg:address per VBO using address fields "
                    "embedded in the PDOK BAG WFS VBO response. Default: true."
                ),
            },
            "include_energy_labels": {
                "type": "boolean",
                "description": (
                    "Download EP-online and emit nrg3:EnergyPerformanceCertificate "
                    "per matched VBO. Requires ep_online_api_key_file. Default: true."
                ),
            },
            "ep_online_api_key_file": {
                "type": "string",
                "minLength": 1,
                "description": (
                    "Path (absolute or relative to this JSON file) to a text file "
                    "containing the EP-online API key."
                ),
            },
            "cache_dir": {
                "type": "string",
                "minLength": 1,
                "description": (
                    "Directory used to cache BAG responses, 3DBAG tiles, and the "
                    "EP-online CSV. Relative paths are resolved against this JSON."
                ),
            },
            "output": {
                "type": "string",
                "minLength": 1,
                "description": "Output .gml file path (created with parent dirs).",
            },
            "srs_name": {
                "type": "string",
                "minLength": 1,
                "description": (
                    "CRS URN written onto gml:Envelope, gml:MultiSurface, "
                    f"gml:Solid. Defaults to {DEFAULT_SRS_NAME} (RD + NAP)."
                ),
            },
            "srs_dimension": {
                "type": "integer",
                "enum": [2, 3],
                "description": "Coordinate dimension. Defaults to 3.",
            },
            "city_model": {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "name": {"type": "string"},
                    "description": {"type": "string"},
                },
            },
            "gml_id_prefix": {
                "type": "string",
                "description": (
                    "Optional NCName prefix prepended to every generated gml:id. "
                    "Useful when merging multiple city builds into one document."
                ),
                "pattern": r"^(?:[A-Za-z_][A-Za-z0-9_.\-]*)?$",
            },
        },
    }


def main() -> int:
    schema = build_schema()
    SCHEMA_PATH.write_text(
        json.dumps(schema, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {SCHEMA_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
