"""Regenerate ``schemas/city_input.schema.json`` from the city-builder config.

The JSON schema is derived from :mod:`citygml_energy.city_builder.config`
so IDE autocomplete always reflects the real loader validation. A CI
test (``tests/test_city_input_schema.py``) refuses to let the committed
file drift out of sync.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = REPO_ROOT / "schemas" / "city_input.schema.json"

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from citygml_energy.city_builder.config import (
    _CBS_POSTCODE6_YEAR_MAX,
    _CBS_POSTCODE6_YEAR_MIN,
    ALLOWED_LODS,
)
from citygml_energy.city_builder.solar_panels import DEFAULT_Z_OFFSET_M
from citygml_energy.namespaces import DEFAULT_SRS_NAME


def build_schema() -> dict[str, Any]:
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://example.invalid/schemas/city_input.schema.json",
        "title": "CityGML Energy City-Build Input",
        "description": (
            "Configuration for the city-scale builder "
            "(citygml_energy.city_builder). Generated by "
            "tools/generate_city_input_schema.py; do not edit by hand."
        ),
        "type": "object",
        "required": ["municipality", "output"],
        "additionalProperties": False,
        "properties": {
            "$schema": {"type": "string"},
            "municipality": {
                "type": "string",
                "minLength": 1,
                "description": (
                    "Dutch municipality name as used by PDOK "
                    "bestuurlijkegebieden (case-insensitive)."
                ),
            },
            "bbox": {
                "type": "array",
                "description": (
                    "Optional [minx, miny, maxx, maxy] in EPSG:28992 to narrow "
                    "the fetch further than the municipality outline. Mutually "
                    "exclusive with 'boundary'."
                ),
                "minItems": 4,
                "maxItems": 4,
                "items": {"type": "number"},
            },
            "boundary": {
                "type": "object",
                "description": (
                    "Optional free-form (possibly concave) polygon. When set, the "
                    "fetch extent is derived from the polygon's own bounds, and "
                    "buildings whose 2D LoD 0 footprint does not intersect the "
                    "polygon are dropped. Mutually exclusive with 'bbox'. Must be "
                    "a GeoJSON file (.geojson / .json) whose root is a single "
                    "Feature (or a FeatureCollection carrying exactly one Feature, "
                    "the QGIS default export shape) with a Polygon or MultiPolygon "
                    "geometry in EPSG:28992."
                ),
                "additionalProperties": False,
                "required": ["path"],
                "properties": {
                    "path": {
                        "type": "string",
                        "minLength": 1,
                        "description": (
                            "Path to a GeoJSON (.geojson / .json) file in "
                            "EPSG:28992 with a single Polygon or MultiPolygon "
                            "Feature (or a one-Feature FeatureCollection), "
                            "absolute or relative to this JSON file."
                        ),
                    },
                },
            },
            "lods": {
                "type": "array",
                "description": "Subset of 3DBAG LoDs to attach per building.",
                "items": {"type": "integer", "enum": sorted(ALLOWED_LODS)},
                "minItems": 1,
                "uniqueItems": True,
            },
            "include_addresses": {
                "type": "boolean",
                "description": (
                    "Emit bldg:address per VBO using address fields "
                    "embedded in the PDOK BAG WFS VBO response. Default: true."
                ),
            },
            "include_energy_labels": {
                "type": "boolean",
                "description": (
                    "Download EP-online and emit nrg3:EnergyPerformanceCertificate "
                    "per matched VBO. Requires EP_ONLINE_API_KEY env var or ep_online_api_key_file. Default: true."
                ),
            },
            "ep_online_api_key_file": {
                "type": "string",
                "minLength": 1,
                "description": (
                    "Optional: path (absolute or relative to this JSON file) to a text file "
                    "containing the EP-online API key. If not set, the loader falls back to "
                    "EP_ONLINE_API_KEY environment variable (e.g., via .env file)."
                ),
            },
            "cache_dir": {
                "type": "string",
                "minLength": 1,
                "description": (
                    "Directory used to cache BAG responses, 3DBAG tiles, and the "
                    "EP-online CSV. Relative paths are resolved against this JSON."
                ),
            },
            "output": {
                "type": "string",
                "minLength": 1,
                "description": "Output .gml file path (created with parent dirs).",
            },
            "srs_name": {
                "type": "string",
                "minLength": 1,
                "description": (
                    "CRS URN written onto gml:Envelope, gml:MultiSurface, "
                    f"gml:Solid. Defaults to {DEFAULT_SRS_NAME} (RD + NAP)."
                ),
            },
            "srs_dimension": {
                "type": "integer",
                "enum": [2, 3],
                "description": "Coordinate dimension. Defaults to 3.",
            },
            "city_model": {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "name": {"type": "string"},
                    "description": {"type": "string"},
                },
            },
            "gml_id_prefix": {
                "type": "string",
                "description": (
                    "Optional NCName prefix prepended to every generated gml:id. "
                    "Useful when merging multiple city builds into one document."
                ),
                "pattern": r"^(?:[A-Za-z_][A-Za-z0-9_.\-]*)?$",
            },
            "solar_panels": {
                "type": "object",
                "description": (
                    "Optional external solar panel polygon source. When set, "
                    "the pipeline attaches one nrg3:GenericSolarCollector per "
                    "panel to the Building with the largest 2D LoD 2 roof "
                    "overlap. The technology-agnostic GenericSolarCollector is "
                    "emitted (rather than PhotovoltaicCollector) because the "
                    "aerial-imagery source has no cell-type metadata. Geometry "
                    "is stamped flat at the roof plane Z evaluated at the "
                    "panel centroid plus z_offset_m."
                ),
                "additionalProperties": False,
                "required": ["path", "layer"],
                "properties": {
                    "path": {
                        "type": "string",
                        "minLength": 1,
                        "description": (
                            "Path to an OGC GeoPackage (.gpkg) in EPSG:28992, "
                            "absolute or relative to this JSON file."
                        ),
                    },
                    "layer": {
                        "type": "string",
                        "minLength": 1,
                        "description": (
                            "Name of the features table inside the GeoPackage "
                            "holding the panel polygons."
                        ),
                    },
                    "z_offset_m": {
                        "type": "number",
                        "description": (
                            "Flat Z offset above the roof plane, in metres. "
                            f"Defaults to {DEFAULT_Z_OFFSET_M}."
                        ),
                    },
                },
            },
            "vegetation": {
                "type": "object",
                "description": (
                    "Optional path to a merged CFTree CityJSON file "
                    "(https://github.com/NoahAlting/CFTree, pre-processed "
                    "via tools/merge_cftree_tiles.py). When set, the "
                    "pipeline emits one veg:SolitaryVegetationObject per "
                    "tree inside the bbox or boundary polygon, with LoD3 "
                    "crown + trunk MultiSurface geometry and CFTree "
                    "morphometrics (height, trunkDiameter, crownDiameter, "
                    "plus porosity/r50/median_z as gen:doubleAttribute)."
                ),
                "additionalProperties": False,
                "required": ["path"],
                "properties": {
                    "path": {
                        "type": "string",
                        "minLength": 1,
                        "pattern": r"\.city\.json$",
                        "description": (
                            "Path to a merged CityJSON 2.0 file (must end "
                            "in '.city.json'), absolute or relative to "
                            "this JSON file. Produced by "
                            "tools/merge_cftree_tiles.py from CFTree "
                            "per-tile output."
                        ),
                    },
                },
            },
            "cbs_postcode6": {
                "type": "object",
                "description": (
                    "Optional CBS Postcode6 dwelling-energy aggregates "
                    "from PDOK's CBS WFS. When set, the pipeline emits "
                    "one nrg3:UrbanFunctionArea per postcode polygon "
                    "intersecting the build extent, carrying the polygon "
                    "geometry, groupMember xlinks to constituent "
                    "buildings, and up to two nrg3:Energy resources "
                    "(naturalGas m3/yr/dwelling, electricity "
                    "kWh/yr/dwelling, type=actual). Suppressed CBS values "
                    "(<6 occupied dwellings privacy rule) translate to "
                    "no resource emitted."
                ),
                "additionalProperties": False,
                "required": ["year"],
                "properties": {
                    "year": {
                        "type": "integer",
                        "minimum": _CBS_POSTCODE6_YEAR_MIN,
                        "maximum": _CBS_POSTCODE6_YEAR_MAX,
                        "description": (
                            "CBS publication vintage to fetch. Selects "
                            "the PDOK WFS endpoint URL. Per CBS's "
                            "documented one-year offset, vintage 2024 "
                            "covers 2023 calendar-year consumption."
                        ),
                    },
                },
            },
        },
    }


def main() -> int:
    schema = build_schema()
    SCHEMA_PATH.write_text(
        json.dumps(schema, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {SCHEMA_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
